create extension if not exists vector with schema extensions;

create schema if not exists panenin_ai_lab;

revoke all privileges on schema panenin_ai_lab from public, anon, authenticated, service_role;
grant usage on schema panenin_ai_lab to service_role;

create table panenin_ai_lab.knowledge_documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null,
  status text not null default 'active'
    check (status in ('active', 'archived')),
  version integer not null default 1
    check (version > 0),
  created_at timestamptz not null default now(),
  unique (title, version)
);

create table panenin_ai_lab.knowledge_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null
    references panenin_ai_lab.knowledge_documents(id)
    on delete cascade,
  chunk_index integer not null
    check (chunk_index >= 0),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(768) not null,
  created_at timestamptz not null default now(),
  unique (document_id, chunk_index)
);

create index knowledge_chunks_embedding_idx
  on panenin_ai_lab.knowledge_chunks
  using hnsw (embedding extensions.vector_cosine_ops);

create function panenin_ai_lab.match_knowledge(
  query_embedding extensions.vector(768),
  match_threshold double precision default 0.62,
  match_count integer default 5
)
returns table (
  chunk_id bigint,
  title text,
  content text,
  similarity double precision
)
language sql
stable
security invoker
set search_path = panenin_ai_lab, extensions, pg_temp
as $function$
  select
    kc.id as chunk_id,
    kd.title,
    kc.content,
    (1 - (kc.embedding <=> query_embedding))::double precision
      as similarity
  from panenin_ai_lab.knowledge_chunks kc
  join panenin_ai_lab.knowledge_documents kd
    on kd.id = kc.document_id
  where kd.status = 'active'
    and (1 - (kc.embedding <=> query_embedding))
      >= greatest(0, least(match_threshold, 1))
  order by kc.embedding <=> query_embedding
  limit greatest(1, least(match_count, 20));
$function$;

create table panenin_ai_lab.incoming_messages (
  id uuid primary key default gen_random_uuid(),
  provider_message_id text not null unique,
  sender text not null,
  message_type text not null,
  text_body text,
  raw_payload jsonb not null,
  status text not null default 'received'
    check (status in ('received', 'processed', 'failed')),
  received_at timestamptz not null default now()
);

create table panenin_ai_lab.conversation_sessions (
  sender text primary key,
  current_intent text,
  state text not null default 'idle',
  context jsonb not null default '{}'::jsonb,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table panenin_ai_lab.knowledge_documents enable row level security;
alter table panenin_ai_lab.knowledge_chunks enable row level security;
alter table panenin_ai_lab.incoming_messages enable row level security;
alter table panenin_ai_lab.conversation_sessions enable row level security;

revoke all privileges on all tables in schema panenin_ai_lab
  from public, anon, authenticated, service_role;
revoke all privileges on all sequences in schema panenin_ai_lab
  from public, anon, authenticated, service_role;
revoke all privileges on all functions in schema panenin_ai_lab
  from public, anon, authenticated, service_role;

grant select, insert, update
  on table panenin_ai_lab.knowledge_documents
  to service_role;
grant select, insert, delete
  on table panenin_ai_lab.knowledge_chunks
  to service_role;
grant select, insert
  on table panenin_ai_lab.incoming_messages
  to service_role;
grant select, insert, update
  on table panenin_ai_lab.conversation_sessions
  to service_role;
grant usage, select
  on sequence panenin_ai_lab.knowledge_chunks_id_seq
  to service_role;
grant execute
  on function panenin_ai_lab.match_knowledge(
    extensions.vector,
    double precision,
    integer
  )
  to service_role;
